from __future__ import annotations

import csv
import json
import os
import re
import shutil
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Sequence

from .io import ensure_dir, write_json


@dataclass(frozen=True)
class BaselineCheck:
    name: str
    ok: bool
    detail: str


@dataclass
class BaselineStatus:
    llm4vkg_root: Path
    checks: list[BaselineCheck] = field(default_factory=list)

    @property
    def ok(self) -> bool:
        return all(check.ok for check in self.checks)

    def to_jsonable(self) -> dict[str, object]:
        return {
            "llm4vkg_root": str(self.llm4vkg_root),
            "ok": self.ok,
            "checks": [check.__dict__ for check in self.checks],
        }


def default_llm4vkg_root(rodi_root: Path) -> Path:
    return rodi_root / "tools" / "LLM4VKG" / "LLM4VKG"


def check_llm4vkg_resources(llm4vkg_root: Path, require_logmap: bool = False) -> BaselineStatus:
    checks = [
        BaselineCheck("root", llm4vkg_root.exists(), str(llm4vkg_root)),
        BaselineCheck("pyproject", (llm4vkg_root / "pyproject.toml").exists(), "pyproject.toml"),
        BaselineCheck("uv", shutil.which("uv") is not None, shutil.which("uv") or "uv not on PATH"),
        BaselineCheck("ontop", _ontop_exists(llm4vkg_root), "resources/ontop/ontop"),
    ]
    if require_logmap:
        checks.append(
            BaselineCheck(
                "logmap",
                bool(list((llm4vkg_root / "resources" / "logmap").glob("**/*logmap*.jar"))),
                "resources/logmap/**/*logmap*.jar",
            )
        )
    return BaselineStatus(llm4vkg_root=llm4vkg_root, checks=checks)


def _ontop_exists(llm4vkg_root: Path) -> bool:
    candidates = [
        llm4vkg_root / "resources" / "ontop" / "ontop",
        llm4vkg_root / "resources" / "ontop" / "ontop.bat",
        llm4vkg_root / "resources" / "ontop" / "bin" / "ontop",
        llm4vkg_root / "resources" / "ontop" / "bin" / "ontop.bat",
    ]
    return any(path.exists() for path in candidates)


def write_llm4vkg_config(
    llm4vkg_root: Path,
    api_names: Sequence[str],
    subset_names: Sequence[str] = ("rodi",),
    db_host: str = "localhost",
    db_port: int = 5432,
    db_user: str = "postgres",
    db_password: str = "postgres",
) -> Path:
    config = llm4vkg_root / "config.py"
    api_names_repr = "[" + ", ".join(repr(name) for name in api_names) + "]"
    subset_names_repr = "[" + ", ".join(repr(name) for name in subset_names) + "]"
    config.write_text(
        "\n".join(
            [
                "# Generated by coding_fgf. Do not commit secrets.",
                "import os",
                "",
                "db_config = {",
                f"    'host': os.getenv('DB_HOST', {db_host!r}),",
                f"    'port': int(os.getenv('DB_PORT', {str(db_port)!r})),",
                f"    'user': os.getenv('POSTGRES_USER', {db_user!r}),",
                f"    'password': os.getenv('POSTGRES_PASSWORD', {db_password!r}),",
                "}",
                f"api_names = {api_names_repr}",
                f"subset_names = {subset_names_repr}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    return config


def sync_llm4vkg_devset(devset_root: Path, llm4vkg_root: Path, scenarios: Sequence[str]) -> Path:
    target = llm4vkg_root / "datasets" / "rodi"
    ensure_dir(target)
    for scenario in scenarios:
        src = devset_root / scenario
        dst = target / scenario
        if not src.exists():
            raise FileNotFoundError(f"Missing devset scenario {src}")
        if dst.exists():
            shutil.rmtree(dst)
        shutil.copytree(src, dst)
    return target


def db_load_commands(
    devset_root: Path,
    scenarios: Sequence[str],
    db_host: str,
    db_port: int,
    db_user: str,
    db_name: str = "postgres",
) -> list[list[str]]:
    commands: list[list[str]] = []
    for scenario in scenarios:
        dump = devset_root / scenario / "dump.sql"
        commands.append(
            [
                "psql",
                "-h",
                db_host,
                "-p",
                str(db_port),
                "-U",
                db_user,
                "-d",
                db_name,
                "-v",
                "ON_ERROR_STOP=1",
                "-f",
                str(dump),
            ]
        )
    return commands


def default_search_path_from_dump(dump: Path) -> str | None:
    text = dump.read_text(encoding="utf-8", errors="replace")
    match = re.search(r"^\s*SET\s+search_path\s*=\s*([^;]+);", text, flags=re.IGNORECASE | re.MULTILINE)
    if not match:
        return None
    schemas = [
        part.strip().strip('"')
        for part in match.group(1).split(",")
        if part.strip() and part.strip().lower() != "pg_catalog"
    ]
    if not schemas or schemas == ["public"]:
        return None
    quoted = [f'"{schema.replace(chr(34), chr(34) + chr(34))}"' for schema in schemas]
    if "public" not in schemas:
        quoted.append("public")
    return ", ".join(quoted)


def load_postgres_dumps(
    devset_root: Path,
    scenarios: Sequence[str],
    db_host: str,
    db_port: int,
    db_user: str,
    db_password: str,
    db_name: str,
    dry_run: bool = False,
    loader: str = "psql",
    compose_root: Path | None = None,
    reset_databases: bool = False,
) -> list[dict[str, object]]:
    if loader == "docker-compose":
        return load_postgres_dumps_docker(
            devset_root,
            scenarios,
            db_user=db_user,
            compose_root=compose_root or devset_root,
            dry_run=dry_run,
            reset_databases=reset_databases,
        )
    rows: list[dict[str, object]] = []
    env = os.environ.copy()
    env["PGPASSWORD"] = db_password
    for scenario in scenarios:
        check_cmd = ["psql", "-h", db_host, "-p", str(db_port), "-U", db_user, "-d", db_name, "-tAc", f"SELECT 1 FROM pg_database WHERE datname='{scenario}'"]
        drop_cmd = ["psql", "-h", db_host, "-p", str(db_port), "-U", db_user, "-d", db_name, "-c", f'DROP DATABASE IF EXISTS "{scenario}"']
        create_cmd = ["psql", "-h", db_host, "-p", str(db_port), "-U", db_user, "-d", db_name, "-c", f'CREATE DATABASE "{scenario}"']
        load_cmd = [
            "psql",
            "-h",
            db_host,
            "-p",
            str(db_port),
            "-U",
            db_user,
            "-d",
            scenario,
            "-v",
            "ON_ERROR_STOP=1",
            "-f",
            str(devset_root / scenario / "dump.sql"),
        ]
        search_path = default_search_path_from_dump(devset_root / scenario / "dump.sql")
        search_path_cmd = [
            "psql",
            "-h",
            db_host,
            "-p",
            str(db_port),
            "-U",
            db_user,
            "-d",
            db_name,
            "-c",
            f'ALTER DATABASE "{scenario}" SET search_path = {search_path}',
        ] if search_path else None
        if dry_run:
            commands = [drop_cmd, create_cmd, load_cmd] if reset_databases else [check_cmd, create_cmd, load_cmd]
            rows.append({"scenario": scenario, "commands": commands, "dry_run": True})
            continue
        if reset_databases:
            drop = run_command(drop_cmd, cwd=devset_root, env=env, timeout=60)
            rows.append({"scenario": scenario, "step": "drop_db", **drop})
            if drop["returncode"] != 0:
                break
            create = run_command(create_cmd, cwd=devset_root, env=env, timeout=60)
            rows.append({"scenario": scenario, "step": "create_db", **create})
            if create["returncode"] != 0:
                break
            load = run_command(load_cmd, cwd=devset_root, env=env, timeout=300)
            rows.append({"scenario": scenario, "step": "load_dump", **load})
            if load["returncode"] != 0:
                break
            if search_path_cmd:
                set_path = run_command(search_path_cmd, cwd=devset_root, env=env, timeout=60)
                rows.append({"scenario": scenario, "step": "set_search_path", **set_path})
                if set_path["returncode"] != 0:
                    break
            continue
        check = run_command(check_cmd, cwd=devset_root, env=env, timeout=60)
        rows.append({"scenario": scenario, "step": "check_db", **check})
        if check["returncode"] != 0:
            break
        if str(check.get("stdout", "")).strip() != "1":
            create = run_command(create_cmd, cwd=devset_root, env=env, timeout=60)
            rows.append({"scenario": scenario, "step": "create_db", **create})
            if create["returncode"] != 0:
                break
        load = run_command(load_cmd, cwd=devset_root, env=env, timeout=300)
        rows.append({"scenario": scenario, "step": "load_dump", **load})
        if load["returncode"] != 0:
            break
        if search_path_cmd:
            set_path = run_command(search_path_cmd, cwd=devset_root, env=env, timeout=60)
            rows.append({"scenario": scenario, "step": "set_search_path", **set_path})
            if set_path["returncode"] != 0:
                break
    return rows


def load_postgres_dumps_docker(
    devset_root: Path,
    scenarios: Sequence[str],
    db_user: str,
    compose_root: Path,
    dry_run: bool = False,
    reset_databases: bool = False,
) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for scenario in scenarios:
        check_cmd = ["docker", "compose", "exec", "-T", "postgres", "psql", "-U", db_user, "-d", "postgres", "-tAc", f"SELECT 1 FROM pg_database WHERE datname='{scenario}'"]
        drop_cmd = ["docker", "compose", "exec", "-T", "postgres", "psql", "-U", db_user, "-d", "postgres", "-c", f'DROP DATABASE IF EXISTS "{scenario}"']
        create_cmd = ["docker", "compose", "exec", "-T", "postgres", "psql", "-U", db_user, "-d", "postgres", "-c", f'CREATE DATABASE "{scenario}"']
        load_cmd = ["docker", "compose", "exec", "-T", "postgres", "psql", "-U", db_user, "-d", scenario, "-v", "ON_ERROR_STOP=1"]
        search_path = default_search_path_from_dump(devset_root / scenario / "dump.sql")
        search_path_cmd = [
            "docker",
            "compose",
            "exec",
            "-T",
            "postgres",
            "psql",
            "-U",
            db_user,
            "-d",
            "postgres",
            "-c",
            f'ALTER DATABASE "{scenario}" SET search_path = {search_path}',
        ] if search_path else None
        if dry_run:
            commands = [drop_cmd, create_cmd, load_cmd] if reset_databases else [check_cmd, create_cmd, load_cmd]
            rows.append({"scenario": scenario, "commands": commands, "dry_run": True})
            continue
        if reset_databases:
            drop = run_command(drop_cmd, cwd=compose_root, timeout=60)
            rows.append({"scenario": scenario, "step": "drop_db", **drop})
            if drop["returncode"] != 0:
                break
            create = run_command(create_cmd, cwd=compose_root, timeout=60)
            rows.append({"scenario": scenario, "step": "create_db", **create})
            if create["returncode"] != 0:
                break
            dump_text = (devset_root / scenario / "dump.sql").read_text(encoding="utf-8", errors="replace")
            load = run_command(load_cmd, cwd=compose_root, input_text=dump_text, timeout=300)
            rows.append({"scenario": scenario, "step": "load_dump", **load})
            if load["returncode"] != 0:
                break
            if search_path_cmd:
                set_path = run_command(search_path_cmd, cwd=compose_root, timeout=60)
                rows.append({"scenario": scenario, "step": "set_search_path", **set_path})
                if set_path["returncode"] != 0:
                    break
            continue
        check = run_command(check_cmd, cwd=compose_root, timeout=60)
        rows.append({"scenario": scenario, "step": "check_db", **check})
        if check["returncode"] != 0:
            break
        if str(check.get("stdout", "")).strip() != "1":
            create = run_command(create_cmd, cwd=compose_root, timeout=60)
            rows.append({"scenario": scenario, "step": "create_db", **create})
            if create["returncode"] != 0:
                break
        dump_text = (devset_root / scenario / "dump.sql").read_text(encoding="utf-8", errors="replace")
        load = run_command(load_cmd, cwd=compose_root, input_text=dump_text, timeout=300)
        rows.append({"scenario": scenario, "step": "load_dump", **load})
        if load["returncode"] != 0:
            break
        if search_path_cmd:
            set_path = run_command(search_path_cmd, cwd=compose_root, timeout=60)
            rows.append({"scenario": scenario, "step": "set_search_path", **set_path})
            if set_path["returncode"] != 0:
                break
    return rows


def java_env(java_home: Path | None = None) -> dict[str, str]:
    env = os.environ.copy()
    env["PYTHONIOENCODING"] = "utf-8"
    env["PYTHONUTF8"] = "1"
    if java_home:
        env["JAVA_HOME"] = str(java_home)
        env["PATH"] = str(java_home / "bin") + os.pathsep + env.get("PATH", "")
    return env


def run_llm4vkg_commands(
    llm4vkg_root: Path,
    scenarios: Sequence[str],
    api_names: Sequence[str],
    run_generation: bool,
    run_evaluation: bool,
    java_home: Path | None = None,
    lightweight_retriever: bool = False,
) -> list[dict[str, object]]:
    commands: list[list[str]] = []
    if run_generation or run_evaluation:
        if os.getenv("CODING_FGF_CPU_TORCH") == "1":
            commands.extend([["uv", "sync"], ["uv", "pip", "install", *_uv_python_args(), "psycopg2-binary"]])
        else:
            commands.extend([["uv", "sync"], ["uv", "pip", "install", "psycopg2-binary"]])
    if run_generation:
        runner = write_filtered_runner(llm4vkg_root, scenarios, lightweight_retriever=lightweight_retriever)
        commands.append(["uv", "run", "python", str(runner.name)])
    if run_evaluation:
        eval_paths = [str(Path("outputs") / "rodi" / f"LLM4VKG_{api}") for api in api_names]
        eval_runner = write_eval_runner(llm4vkg_root, scenarios=scenarios, eval_paths=eval_paths)
        commands.append(["uv", "run", "python", str(eval_runner.name)])
    results: list[dict[str, object]] = []
    env = java_env(java_home)
    for command in commands:
        result = run_command(command, cwd=llm4vkg_root, env=env, timeout=3600)
        results.append(result)
        if result["returncode"] != 0:
            break
    return results


def _uv_python_args() -> list[str]:
    env_path = os.getenv("UV_PROJECT_ENVIRONMENT")
    if not env_path:
        return []
    executable = Path(env_path) / ("Scripts/python.exe" if os.name == "nt" else "bin/python")
    return ["--python", str(executable)]


def run_command(
    command: Sequence[str],
    cwd: Path,
    env: dict[str, str] | None = None,
    input_text: str | None = None,
    timeout: int = 300,
) -> dict[str, object]:
    proc = subprocess.run(
        list(command),
        cwd=cwd,
        env=env,
        input=None if input_text is None else input_text.encode("utf-8"),
        capture_output=True,
        timeout=timeout,
    )
    stdout = (proc.stdout or b"").decode("utf-8", errors="replace")
    stderr = (proc.stderr or b"").decode("utf-8", errors="replace")
    return {"command": list(command), "returncode": proc.returncode, "stdout": stdout[-4000:], "stderr": stderr[-4000:]}


def write_eval_runner(llm4vkg_root: Path, scenarios: Sequence[str], eval_paths: Sequence[str]) -> Path:
    runner = llm4vkg_root / "coding_fgf_rodi_eval_runner.py"
    runner.write_text(
        f"""
from __future__ import annotations

import os
import subprocess
import sys
import time
import traceback

import psycopg2

from config import db_config
import src.vkg_utils.evaluate_pipeline as ep

SCENARIOS = {list(scenarios)!r}
EVAL_PATHS = {list(eval_paths)!r}

def ontop_command(ontop_cli_path: str) -> str:
    names = ["ontop.bat", "ontop.cmd", "ontop.exe"] if os.name == "nt" else ["ontop"]
    for name in names:
        candidate = os.path.join(ontop_cli_path, name)
        if os.path.exists(candidate):
            return candidate
    return os.path.join(ontop_cli_path, "ontop")

def convert_ttl_to_obda(input_ttl, output_obda, ontop_cli_path):
    command = [
        ontop_command(ontop_cli_path), "mapping", "to-obda",
        "-i", input_ttl.replace("\\\\", "/"),
        "-o", output_obda.replace("\\\\", "/"),
    ]
    subprocess.run(command, check=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE, timeout=300)
    print(f"[coding_fgf] Converted {{input_ttl}} -> {{output_obda}}")

def start_ontop_endpoint(mapping_file, ontology_file, property_file, ontop_cli_path):
    command = [
        ontop_command(ontop_cli_path), "endpoint",
        "-m", mapping_file.replace("\\\\", "/"),
        "-t", ontology_file.replace("\\\\", "/"),
        "-p", property_file.replace("\\\\", "/"),
        "--port", ep.endpoint_port,
        "--cors-allowed-origins=*",
    ]
    print(f"[coding_fgf] Starting Ontop: {{' '.join(command)}}")
    subprocess.Popen(command)
    time.sleep(20)

def execute_sql_query(dbname, sql_query):
    conn = psycopg2.connect(
        dbname=dbname,
        user=db_config["user"],
        password=db_config["password"],
        host=db_config["host"],
        port=db_config["port"],
    )
    try:
        cur = conn.cursor()
        cur.execute(f"SET search_path TO {{dbname}}, public;")
        conn.commit()
        cur.execute(sql_query)
        rows = cur.fetchall()
    finally:
        conn.close()
    results = []
    for row in rows:
        values = [str(value) for value in row]
        results.append(values[0] if len(values) == 1 else values)
    return results

ep.convert_ttl_to_obda = convert_ttl_to_obda
ep.start_ontop_endpoint = start_ontop_endpoint
ep.execute_sql_query = execute_sql_query

def evaluate_without_ontology_matching(db_name: str, base_path: str) -> None:
    ontop_cli_path = os.path.abspath(os.path.join("./resources", "ontop"))
    ttl_mapping_file = os.path.join(base_path, f"rodi_{{db_name}}_generated_mapping.ttl")
    ontology_file = os.path.join(base_path, f"rodi_{{db_name}}_generated_ontology.ttl")
    property_file = os.path.join(base_path, "ontology.properties")
    qpair_folder = os.path.join("datasets", "rodi", db_name, "queries")
    output_metrics_path = os.path.join(base_path, "metrics_details.json")
    output_f1_path = os.path.join(base_path, "f1.txt")
    ep.run_evaluation_pipeline(
        ttl_mapping_file=ttl_mapping_file,
        ontology_file=ontology_file,
        property_file=property_file,
        qpair_folder=qpair_folder,
        dbname=db_name,
        ontop_cli_path=ontop_cli_path,
        output_metrics_path=output_metrics_path,
        output_f1_path=output_f1_path,
    )

failures = []
for eval_path in EVAL_PATHS:
    for scenario in SCENARIOS:
        base_path = os.path.join(eval_path, scenario)
        if not os.path.isdir(base_path):
            print(f"[coding_fgf] Missing baseline output: {{base_path}}")
            failures.append((scenario, "missing output"))
            continue
        try:
            evaluate_without_ontology_matching(scenario, base_path)
        except Exception as exc:
            print(f"[coding_fgf] Evaluation failed for {{scenario}}: {{type(exc).__name__}}: {{exc}}")
            traceback.print_exc()
            failures.append((scenario, str(exc)))

if failures:
    print(f"[coding_fgf] Evaluation failures: {{failures}}")
    sys.exit(1)
""".lstrip(),
        encoding="utf-8",
    )
    return runner


def write_filtered_runner(llm4vkg_root: Path, scenarios: Sequence[str], lightweight_retriever: bool = False) -> Path:
    runner = llm4vkg_root / "coding_fgf_llm4vkg_runner.py"
    runner.write_text(
        f"""
from __future__ import annotations

import os
import json
import traceback

import torch
from config import api_names, db_config
from src.db_utils.db_utils import get_table_structure
from src.llm.utils.langchain_utils import Modules
from src.utils.tools import load_json_file
from src.vkg_generation.VKGDatasets import OntologyDataset, TableDataset
from src.vkg_generation.mapping_pattern_recognition import DBSchemaGraph
from src.vkg_generation.ontology_completion_mapping_generation import MappingGeneration, OntologyCompletion

SCENARIOS = {list(scenarios)!r}
MAPPING_PATTERN_DIR = "outputs/mapping_patterns"
LIGHTWEIGHT_RETRIEVER = {bool(lightweight_retriever)!r}

def configure_api_from_env() -> None:
    api_key = os.getenv("OPENAI_API_KEY") or os.getenv("LLM4VKG_API_KEY")
    if not api_key:
        return
    api_id = os.getenv("LLM4VKG_API_ID", "gpt_4o")
    model = os.getenv("LLM4VKG_MODEL", os.getenv("OPENAI_MODEL", "gpt-4o"))
    base_url = os.getenv("OPENAI_BASE_URL", "https://api.openai.com/v1")
    path = os.path.join("src", "llm", "resources", "ampi.json")
    with open(path, "w", encoding="utf-8") as fh:
        json.dump({{
            api_id: {{
                "url": base_url,
                "api_key": api_key,
                "model": model,
                "history": []
            }}
        }}, fh, indent=2)

def configure_lightweight_retriever() -> None:
    import src.vkg_generation.ontology_completion_mapping_generation as oc_module

    original_sentence_transformer = oc_module.SentenceTransformer
    if not LIGHTWEIGHT_RETRIEVER:
        class CpuSentenceTransformer(original_sentence_transformer):
            def __init__(self, model_name_or_path=None, *args, **kwargs):
                if kwargs.get("device") == "cuda":
                    kwargs["device"] = "cpu"
                super().__init__(model_name_or_path, *args, **kwargs)

        oc_module.SentenceTransformer = CpuSentenceTransformer
        return

    import hashlib
    import torch

    class LightweightSentenceTransformer:
        def __init__(self, *args, **kwargs):
            self.dim = 256

        def encode(self, texts, convert_to_tensor=False):
            vectors = []
            for text in texts:
                vec = torch.zeros(self.dim)
                for token in str(text).lower().split() or [str(text)]:
                    digest = hashlib.sha256(token.encode("utf-8")).digest()
                    idx = int.from_bytes(digest[:4], "big") % self.dim
                    vec[idx] += 1.0 if digest[4] % 2 == 0 else -1.0
                norm = torch.linalg.vector_norm(vec)
                if norm.item() > 0:
                    vec = vec / norm
                vectors.append(vec)
            tensor = torch.stack(vectors) if vectors else torch.empty((0, self.dim))
            return tensor if convert_to_tensor else tensor.numpy()

    oc_module.SentenceTransformer = LightweightSentenceTransformer

def run_mpr(dbname: str) -> None:
    db_schema = "mondial_rdf2sql_standard" if dbname.startswith("mondial") else dbname
    base_path = os.path.join(MAPPING_PATTERN_DIR, dbname)
    os.makedirs(base_path, exist_ok=True)
    table_info = get_table_structure(dbname=dbname, db_schema=db_schema, **db_config)
    graph = DBSchemaGraph(table_info=table_info)
    mapping_patterns = {{}}
    for pattern_type in graph.mapping_pattern_types:
        mapping_patterns[pattern_type] = graph.recognize_mapping_pattern(pattern_type)
    torch.save(mapping_patterns, os.path.join(base_path, "mapping_pattern.pt"))

def run_oc_mg(dbname: str, api_name: str) -> None:
    db_schema = "mondial_rdf2sql_standard" if dbname.startswith("mondial") else dbname
    base_path = os.path.join("outputs", "rodi", f"LLM4VKG_{{api_name}}", dbname)
    os.makedirs(base_path, exist_ok=True)
    ontology_path = os.path.join("datasets", "rodi", dbname, "ontology.ttl")
    if not os.path.exists(ontology_path):
        ontology_path = os.path.join("datasets", "rodi", dbname, "ontology.owl")
    ontology_dataset = OntologyDataset(ontology_path)
    table_info = get_table_structure(dbname=dbname, db_schema=db_schema, **db_config)
    table_dataset = TableDataset(table_info)
    strategy = load_json_file("setting/strategy/OntologyCompletion/LLM4VKG.json")
    prompts = load_json_file("prompts/OntologyCompletion/prompt.json")
    modules = Modules(strategy, prompts, set_all_api_id=api_name)
    oc = OntologyCompletion(modules=modules, db_schema=db_schema)
    ontology, db2o = oc.run_ontology_completion(ontology_dataset, table_dataset)
    torch.save(db2o, os.path.join(base_path, "db2o.pt"))
    torch.save(ontology, os.path.join(base_path, "ontology.pt"))
    original_ontology = OntologyDataset(ontology_path)
    pattern_path = os.path.join(MAPPING_PATTERN_DIR, dbname, "mapping_pattern.pt")
    mg = MappingGeneration(modules=modules, db_schema=db_schema)
    mg.run_mapping_generation(
        table=table_dataset,
        db2o=db2o,
        ontology=ontology,
        mapping_patterns=torch.load(pattern_path, weights_only=False),
        original_ontology=original_ontology,
    )
    original_ontology.graph.serialize(
        destination=os.path.join(base_path, f"rodi_{{dbname}}_generated_ontology.ttl"),
        format="turtle",
    )
    mg.mapping.serialize(
        destination=os.path.join(base_path, f"rodi_{{dbname}}_generated_mapping.ttl"),
        format="turtle",
    )

configure_api_from_env()
configure_lightweight_retriever()

for scenario in SCENARIOS:
    try:
        run_mpr(scenario)
        for api in api_names:
            run_oc_mg(scenario, api)
    except Exception as exc:
        print(f"coding_fgf filtered LLM4VKG failed for {{scenario}}: {{type(exc).__name__}}: {{exc}}")
        traceback.print_exc()
        raise
""".lstrip(),
        encoding="utf-8",
    )
    return runner


def discover_llm4vkg_metrics(llm4vkg_root: Path, output_root: Path) -> list[dict[str, object]]:
    rows: list[dict[str, object]] = []
    for f1_path in sorted((llm4vkg_root / "outputs").glob("**/f1.txt")):
        scenario = f1_path.parent.name
        f1 = None
        precision = None
        recall = None
        for line in f1_path.read_text(encoding="utf-8", errors="replace").splitlines():
            if "Average Precision" in line:
                precision = _last_float(line)
            elif "Average Recall" in line:
                recall = _last_float(line)
            elif "Average F1" in line:
                f1 = _last_float(line)
        rows.append({"scenario": scenario, "precision": precision, "recall": recall, "f1": f1, "path": str(f1_path)})
    ensure_dir(output_root)
    with (output_root / "llm4vkg_metrics.csv").open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=["scenario", "precision", "recall", "f1", "path"])
        writer.writeheader()
        writer.writerows(rows)
    return rows


def _last_float(line: str) -> float | None:
    for token in reversed(line.replace(":", " ").split()):
        try:
            return float(token)
        except ValueError:
            continue
    return None


def bootstrap_llm4vkg(
    llm4vkg_root: Path,
    devset_root: Path,
    output_root: Path,
    scenarios: Sequence[str],
    api_names: Sequence[str],
    db_host: str,
    db_port: int,
    db_user: str,
    db_password: str,
    db_name: str,
    run_generation: bool,
    run_evaluation: bool,
    dry_run_db: bool = False,
    java_home: Path | None = None,
    db_loader: str = "psql",
    compose_root: Path | None = None,
    lightweight_retriever: bool = False,
) -> dict[str, object]:
    ensure_dir(output_root)
    status = check_llm4vkg_resources(llm4vkg_root)
    config_path = write_llm4vkg_config(llm4vkg_root, api_names=api_names, db_host=db_host, db_port=db_port, db_user=db_user, db_password=db_password)
    dataset_path = sync_llm4vkg_devset(devset_root, llm4vkg_root, scenarios)
    db_results = load_postgres_dumps(
        devset_root,
        scenarios,
        db_host,
        db_port,
        db_user,
        db_password,
        db_name,
        dry_run=dry_run_db,
        loader=db_loader,
        compose_root=compose_root,
    )
    command_results: list[dict[str, object]] = []
    if status.ok and not dry_run_db:
        command_results = run_llm4vkg_commands(
            llm4vkg_root,
            scenarios=scenarios,
            api_names=api_names,
            run_generation=run_generation,
            run_evaluation=run_evaluation,
            java_home=java_home,
            lightweight_retriever=lightweight_retriever,
        )
    metrics = discover_llm4vkg_metrics(llm4vkg_root, output_root)
    result = {
        "status": status.to_jsonable(),
        "config_path": str(config_path),
        "dataset_path": str(dataset_path),
        "db_results": db_results,
        "command_results": command_results,
        "metrics": metrics,
    }
    write_json(output_root / "llm4vkg_run.json", result)
    return result
